print("Welcome to the tip calculator.")
total_bill = float(input("What was the total bill? $"))
chaev = int(input("What percentage tip would you like to give? 10, 12, or 15? "))
count = int(input("How many people to split the bill? "))
result = round((total_bill+total_bill/100*chaev)/count, 2)
print(f"Each person should pay: ${result}")